spring:
  application:
    name: todoh
  
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp
    username: myuser
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: cdac6c938a4fdef401313a55749b77707c1c635b3f70240762daa0a98b857e7b